### ISSUE TITLE
En tant qu'utilisateur, je peux proposer un skin

### ISSUE THREAD

**Issue by tlegrand54** [Barbofus/BARBOFUS#3]

**Comment by Raphtml** [comment]
A détailler dans la mise en pratique, est-ce qu'on part sur du simple upload de photo ? Si oui du coup des fois les gens mettront les codes couleurs dans leur screen des fois non, des fois ce sera un skin pris du skinator de Dofusbook des fois non, ce sera pas hyper harmonieux si on laisse la liberté d'upload n'importe quel screen à l'utilisateur ?
